#!/bin/sh
# covpct.sh — Extract coverage percentage from a go tool cover report.
#
# Reads a report generated by `go tool cover -func` and extracts
# the total coverage percentage (without the % sign).
#
# Usage:
#   ./covpct.sh [flags]
#
# Example:
#   ./covpct.sh -s ./gate/coverage.report.txt -o ./gate/coverage.pct.txt

set +x

# Resolve the directory this script lives in.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Load getoptions library functions.
eval "$(sh "${SCRIPT_DIR}/getoptions/getoptions.sh" -)"

parser_definition() {
  setup REST help:usage -- \
    "Usage: $0 [flags]" \
    '' \
    'Extract the total coverage percentage from a go tool cover report.' \
    'Reads the "total:" line and outputs the percentage number (without %).' \
    '' \
    'Example:' \
    "  $0 -s ./gate/coverage.report.txt -o ./gate/coverage.pct.txt"
  msg -- '' 'Options:'
  param SOURCE -s --source -- "input file: go tool cover -func report (required)"
  param OUTPUT -o --output -- "output file for the percentage (default: stdout)"
  disp :usage -h --help
}

# Check for --help first, before any other parsing.
for _arg in "$@"; do
  case "${_arg}" in
    -h|--help) eval "$(getoptions_help parser_definition usage "$0")"; usage; exit 0 ;;
  esac
done

eval "$(getoptions parser_definition parse "$0")"
parse "$@"
eval "set -- $REST"

# --- Validation ---

_err=0

if [ -z "${SOURCE}" ]; then
  echo "error: --source is required" >&2
  _err=1
fi

if [ "${_err}" -ne 0 ]; then
  echo "" >&2
  eval "$(getoptions_help parser_definition usage "$0")"
  usage >&2
  exit 1
fi

if [ ! -f "${SOURCE}" ]; then
  echo "error: source file not found: ${SOURCE}" >&2
  exit 1
fi

# --- Extract percentage ---

_pct=""
while IFS= read -r _line; do
  case "${_line}" in
    total:*)
      # The total line looks like: total:	(statements)	98.5%
      # Extract the last field and strip the % sign.
      _pct=$(echo "${_line}" | awk '{print $NF}' | sed 's/%//')
      ;;
  esac
done < "${SOURCE}"

if [ -z "${_pct}" ]; then
  echo "error: no 'total:' line found in ${SOURCE}" >&2
  exit 1
fi

# --- Output ---

if [ -n "${OUTPUT}" ]; then
  echo "${_pct}" > "${OUTPUT}" || {
    echo "error: failed to write to output file: ${OUTPUT}" >&2
    exit 1
  }
  echo "coverage: ${_pct}%" >&2
else
  echo "${_pct}"
fi

exit 0
