#!/bin/sh
# rcgrade.sh — Extract the grade from a goreportcard-cli report.
#
# Reads a report generated by goreportcard-cli and extracts the
# grade letter (e.g. A+, B, C-).
#
# Usage:
#   ./rcgrade.sh [flags]
#
# Example:
#   ./rcgrade.sh -s ./gate/goreportcard.report.txt -o ./gate/goreportcard.grade.txt

set +x

# Resolve the directory this script lives in.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Load getoptions library functions.
eval "$(sh "${SCRIPT_DIR}/getoptions/getoptions.sh" -)"

parser_definition() {
  setup REST help:usage -- \
    "Usage: $0 [flags]" \
    '' \
    'Extract the grade from a goreportcard-cli report.' \
    'Parses the "Grade" line and outputs the grade letter (e.g. A+, B, C-).' \
    '' \
    'Example:' \
    "  $0 -s ./gate/goreportcard.report.txt -o ./gate/goreportcard.grade.txt"
  msg -- '' 'Options:'
  param SOURCE -s --source -- "input file: goreportcard-cli output (required)"
  param OUTPUT -o --output -- "output file for the grade (default: stdout)"
  disp :usage -h --help
}

# Check for --help first, before any other parsing.
for _arg in "$@"; do
  case "${_arg}" in
    -h|--help) eval "$(getoptions_help parser_definition usage "$0")"; usage; exit 0 ;;
  esac
done

eval "$(getoptions parser_definition parse "$0")"
parse "$@"
eval "set -- $REST"

# --- Validation ---

_err=0

if [ -z "${SOURCE}" ]; then
  echo "error: --source is required" >&2
  _err=1
fi

if [ "${_err}" -ne 0 ]; then
  echo "" >&2
  eval "$(getoptions_help parser_definition usage "$0")"
  usage >&2
  exit 1
fi

if [ ! -f "${SOURCE}" ]; then
  echo "error: source file not found: ${SOURCE}" >&2
  exit 1
fi

# --- Extract grade ---

# The goreportcard-cli output contains a line like:
#   Grade .......... A+ 99.9%
# Extract the grade field (second-to-last field on the Grade line).

_grade=""
while IFS= read -r _line; do
  case "${_line}" in
    Grade*)
      # Extract the grade: second-to-last field (grade letter before the percentage).
      _grade=$(echo "${_line}" | awk '{print $(NF-1)}')
      ;;
  esac
done < "${SOURCE}"

if [ -z "${_grade}" ]; then
  echo "error: no 'Grade' line found in ${SOURCE}" >&2
  exit 1
fi

# --- Output ---

if [ -n "${OUTPUT}" ]; then
  echo "${_grade}" > "${OUTPUT}" || {
    echo "error: failed to write to output file: ${OUTPUT}" >&2
    exit 1
  }
  echo "goreportcard grade: ${_grade}" >&2
else
  echo "${_grade}"
fi

exit 0
